name: CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: install pipx
      run: |
        pip install --user pipx
        pipx ensurepath

    - name: install poetry
      run: |
        pipx install poetry

    - name: install dependencies
      run: |
        poetry install --without research

    - name: run ruff
      run: |
        poetry run ruff check .

    - name: run tests
      run: |
        poetry run pytest
